Install the `go-critic` command instead of `gocritic`
The `go-critic` pre-commit hook from the TekWizely/pre-commit-golang
repo expects the binary to be called `go-critic` now. As a result, the
current tool installation in the `build.yml` workflow results in the
following error when pre-commit is run in GitHub Actions:
error: command not found: go-critic